config/routes.rb
Rails.application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  get 'profile/index'
  get 'profile/edit'
  patch 'profile/update'
  put 'profile/update'
  get 'profile/change_password'
  patch 'profile/update_password'
  put 'profile/update_password'

  post 'comments/delete'

  resources :profile

  resources :articles do
    resources :comments
  end

  resources :offers do
    resources :offer_comments
  end

  get 'welcome/index'
  get 'welcome/about_us'
  root 'welcome#index'

  get 'signup' => 'signup#index'
  post 'signup' => 'signup#create'

  get 'articles/new' => 'articles#index'
  post 'articles/new' => 'articles#create'

  get 'articles/:id/chooseComment/:commentId' => 'articles#AddBestComment'

  get 'login' => 'sessions#index'
  post 'login' => 'sessions#login'
  delete 'logout' => 'sessions#logout'

  get ':controller(/:action)'
  get ':controller(/:action(/:id))(.:format)'

  get 'password_resets/index'
  get 'password_resets/new'
  get 'password_resets/index'
  post 'password_resets/index'
  get 'password_resets/create'
  post 'password_resets/create'
  post 'password_resets/edit'
  get 'password_resets/update'
  post 'password_resets/update'

  get 'account_activations/show'
  post 'account_activations/show'

  resources :account_activations, only: [:index]











end

app/models/article.rb
class Article < ActiveRecord::Base

  #With this line you can add votes on each article
  acts_as_votable


  #Articles can have many comments
  has_many :comment, :dependent => :destroy
  has_many :article_attachments, :dependent => :destroy
  belongs_to :user
  belongs_to :topic


  validates :title, :presence => true, :uniqueness => false, :length => { :in => 0..60 }

  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("title LIKE ? OR text LIKE ? OR Tags LIKE ?", "%#{search}%","%#{search}%","%#{search}%")
  end

  def self.searchByTag(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("tags_search LIKE ?","%#{search}%")
  end

  def self.searchByTopic(search)
    # Title is for the above case, the OP incorrectly had 'name'
    topic = Topic.find_by_topic_name(search)
    where("topic_id = "+ topic.id.to_s)
  end

  def self.selectByTopic()
    # Title is for the above case, the OP incorrectly had 'name'
    Topic.joins(:articles).select("topics.topic_name, count(articles.topic_id) as count").group("topics.topic_name")
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # add authentication for all actions
  before_filter :validate_if_user_logged_in, only: [:new ,:create ,:edit, :update, :destroy,:AddBestComment]

  # show all articles
  def index

    if params[:search]
      @articles = Article.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
      @srch = params[:search]
    elsif !params[:popular_tag].nil?
      @articles = Article.searchByTag(params[:popular_tag]).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
      @selected_tag = params[:popular_tag].to_s.remove('[',']')
    elsif !params[:popular_topic].nil?
      @articles = Article.searchByTopic(params[:popular_topic]).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
      @selected_topic = params[:popular_topic].to_s.remove('[',']')
    elsif !params[:most_popular].nil?
      @articles = Article.order("views DESC").paginate(:page => params[:page], :per_page => 5)
      @most_popular = true;
    elsif !params[:my_posts].nil? && !current_user.nil?
      @articles = Article.where("user_id= "+current_user.id.to_s).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
      @my_posts = true;
    else
      @articles = Article.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    end

  end

  # get form page for creating
  def new

  end

  # post action to create a new article
  def create

    article = Article.new(article_params)
    article.user = current_user

    if article.save

      addTopic(topic_params[:topic_name].to_s,article)
      addTagsAndhandleTagCount(article)

      addAttachment(article,false)

      redirect_to articles_path
    else
      $text = article_params[:text];
      $tags = article_params[:Tags];
      $topic = topic_params[:topic_name];
      render 'articles/new'
    end
  end

  # show specific article
  def show
    @article = Article.find_by_id(params[:id]);
    if @article
      @article.views = @article.views + 1;
      @article.save;
    else
      redirect_to welcome_index_path
    end
  end

  # get article for edit
  def edit
    @article = Article.find_by_id(params[:id]);
    if !@article
      redirect_to welcome_index_path
    end
  end

  # post action for editing article
  def update

    article = Article.find(params[:id])
    prevTags = article.Tags
    if article.update(article_params)

      addTopic(topic_params[:topic_name].to_s,article)

      if prevTags != article_params[:Tags]
        handleTagUpdates(prevTags)
        addTagsAndhandleTagCount(article)
      end

      addAttachment(article,true)

      if article.save
        redirect_to articles_path
      else
        render 'edit'
      end
    else
      render 'edit'
    end
  end

  def AddBestComment
    article = Article.find(params[:id])
    if article
      article.accepted_comment_id = params[:commentId]
      if article.save
        redirect_to article_path(article)
      else
        redirect_to login_url()
      end
    end
  end


  # delete specific article
  def destroy

    article = Article.find(params[:id])

    if !article.tags_search.nil?
      split_tags = article.tags_search.to_s.remove('[').to_s.split(']');
      split_tags.each do |tag|
        tempTag = Tag.find_by_name(tag)
        if(!tempTag.nil?)
          tempTag.count -= 1;
          if(tempTag.count == 0)
            tempTag.destroy
          else
            tempTag.save
          end
        end
      end
    end

    article.destroy
    redirect_to articles_path
  end

  def like
    article = Article.find(params[:id]);
    current_user.likes article
    article.views -= 1
    article.save
    redirect_to article_path(article)
  end

  def dislike
    article = Article.find(params[:id]);
    current_user.dislikes article
    article.views -= 1
    article.save
    redirect_to article_path(article)
  end

  # Handle Tags
  def addTagsAndhandleTagCount(article)

    tagsSearch = '';
    #Add count of tags for statistic purposes
    if(!article_params[:Tags].nil?)
      split_tags = article_params[:Tags].to_s.split(',');
      split_tags.each do |tag|
        tempTag = Tag.find_by_name(tag)
        tagsSearch += '['+tag+']'
        if(tempTag.nil?)
          tempTag = Tag.new();
          tempTag.name = tag;
          tempTag.count = 1;
        else
          tempTag.count += 1;
        end
        tempTag.save
      end
      article.tags_search= tagsSearch;
      article.save
    end
  end

  def handleTagUpdates(prevTags)

      split_tags = prevTags.to_s.split(',');
      split_tags.each do |tag|
        tempTag = Tag.find_by_name(tag)
        if(!tempTag.nil?)
          tempTag.count -= 1;
          if(tempTag.count == 0)
            tempTag.destroy
          else
            tempTag.save
          end
        end
      end
  end

  #Method to Add a Topic to the Article
  def addTopic(topic_name,article)
    topic = Topic.where(:topic_name => topic_name).first;
    #Add Topic to the Topic table if new
    if(topic.nil?)
      topic = Topic.new(topic_params)
      topic.save
      article.topic = topic
    else
      article.topic = topic
    end
    article.save
  end

  #Add File Attachment
  def addAttachment(article, isUpdate)
    if !attach_params[:attach_file].nil?
      #Delete PreviousAttachment
      if isUpdate
        _attachments = ArticleAttachment.where("article_id = "+article.id.to_s)
        if _attachments.any?
          _attachments.each do |attachment|
            attachment.destroy
          end
        end
      end
      # Add new Attachment
      article_attachments = ArticleAttachment.new()
      article_attachments.attach_file = attach_params[:attach_file].tempfile
      article_attachments.attach_file_file_name = attach_params[:attach_file].original_filename
      article_attachments.article = article
      article_attachments.save
    end
  end

  private
  def validate_if_user_logged_in
    if !check_login_state
      redirect_to (login_path + '?From='+ request.fullpath)
    end
  end

  # get article object from http params
  def article_params
    params.require(:article).permit(:title, :text,:Tags)
  end

  def topic_params
    params.require(:article).permit(:topic_name)
  end

  def article1_params
    params.require(:article).permit(:search)
  end
  def attach_params
    params.require(:article).permit(:attach_file)
  end

end

app/helpers/article_helper.rb
module ArticleHelper

end

app/views/articles/edit.html.erb
<div class="container">
  <h2 class="page-header">Edit Article</h2>

  <!-- Blog Post_ Content Column -->
  <div class="ui buttons">
    <button class="big ui button" onclick="RedirectToArticles()">
      <i class="arrow circle outline left icon"></i>Back</button>
  </div>

  <hr>

	<%= form_for :article, class:"form form-horizontal",  url:article_path(@article), method: :patch do |f| %>
	<div class="form-group">
    <label>Title <label id="lbl_red">*</label></label>
		<br>
    <%= f.text_field :title, placeholder: "Enter your title...",  class:'form-control',onkeydown:'hideError()',onpaste:'hideError()',value: @article.title %>
    <% if @article != nil && @article.errors.any? %>
        <div class="ui pointing red basic label">
          <% for message_error in @article.errors.full_messages %>
              <%= message_error %>
          <% end %>
        </div>
    <% end %>
	</div>
	<div class="form-group">
		<%= f.label :text %>
		<br>
		<%= f.text_area :text, class:'redactor form-control', value: @article.text.html_safe, placeholder: "Enter text...." %>
 	</div>
  <div class="form-group">
    <%= f.label :Add_Attachment %>
    <br>
    <%= f.file_field :attach_file, class:'filestyle form-control',data: {buttonBefore: "true"} %>
  </div>
  <div class="form-group">
    <label for="select_topic">Topic</label>
    <select  id="select_topic" name="article[topic_name]" class="demo-default" placeholder="Select a topic...">
      <option value="">Select a topic...</option>
      <% Topic.all.each do |topic| %>
          <option value="<%= topic.topic_name%>" <%= if @article.topic
                                                       if @article.topic.topic_name == topic.topic_name
                                                         "selected"
                                                       end
                                                     end %>   ><%= topic.topic_name %></option>
      <% end %>
    </select>
  </div>
  <div class="form-group">
    <label for="input_tags">Tags</label>
    <input type="text" id="input_tags" name="article[Tags]" value="<%= @article.tags_search.to_s.remove('[').to_s.gsub(']',',') %>" class="demo-default">
  </div>

  <div class="form-group">
    <button type="submit" name="commit"  class="big ui teal labeled icon button">
      <i class="save icon"></i>Save</button>
  </div>
	<% end %>

  <script>

    function hideError() {
      document.getElementsByClassName('ui pointing red basic label')[0].style.visibility='hidden';
      document.getElementsByClassName('ui pointing red basic label')[0].style.margin='0';
    }

    function RedirectToArticles() {
      window.location = "<%= articles_url %>/<%= @article.id %>"
    }

    $('#input_tags').selectize({
      delimiter: ',',
      persist: false,
      create: function(input) {
        return {
          value: input,
          text: input
        }
      }
    });

    $('#select_topic').selectize({
      create: true,
      sortField: {
        field: 'text',
        direction: 'asc'
      },
      dropdownParent: 'body'
    });
  </script>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h2 class="page-header">Forum Posts</h2>

  <button class="ui labeled icon button" id="buttonWithMarginBtm"  onclick="RedirectToArticlesNew()">
       <i class="add circle icon"></i>New Post
  </button>


  <div class="row">
      <div class="col-lg-8 col-xs-8">
        <ul class="nav nav-tabs">
          <li role="presentation" <%=if @most_popular.nil? && @my_posts.nil?
                                       "class=active"
                                       end %> ><a href="<%=articles_path%>">Recent Posts</a></li>
          <li role="presentation" <%=if !@most_popular.nil?
                                       "class=active"
                                     end %> > <a href="/articles?most_popular=true">Most Popular</a></li>
          <% if current_user %>
            <li role="presentation" <%=if !@my_posts.nil?
                                         "class=active"
                                       end %> > <a href="/articles?my_posts=true">My Posts</a></li>
          <%end%>
        </ul>
        <!-- Display Posts By popularity -->
        <% @articles.each do |article| %>
          <table width="100%"  >
            <tr>
                 <div class = "ui circular labels">
                   <td id="td_centered"><a class="ui label"><%= number_with_delimiter(article.get_upvotes.size - article.get_downvotes.size) %></a></td>
                   <td id="td_centered"><a class="ui label"><%= number_with_delimiter(article.count_comments) %></a></td>
                   <td id="td_centered"><a class="ui label"><%= number_with_delimiter(article.views) %></a></td>
                 </div>
                 <td rowspan="2">
                   <div>
                     <a id="a_medium" href="<%= article_path(article.id)%>"><%= article.title %></a>
                     <br/>
                     <% if !article.Tags.nil?%>
                         <% tags = article.Tags.split(',')  %>
                           <% tags.take(5).each do |tag| %>
                             <a id="a_small" class="ui teal label"><%= tag %></a>
                           <% end %>
                     <% end %>
                     <% if tags.count > 5 %>
                         <a id="a_small" class="ui teal label">. . . </a>
                     <%end%>
                     <h6 class="pull-right">Posted <%= time_ago_in_words(article.created_at)%> ago by <a href="<%= profile_path(article.user_id) %>"><%= User.find_by(id: article.user_id).name  %></a>.</h6>
                   </div>
                 </td>
            </tr>
            <tr>
                 <td id="td_centered"><h6>votes</h6></td>
                 <td id="td_centered"><h6>comments</h6></td>
                 <td id="td_centered"><h6>views</h6></td>
            </tr>
            <div class="ui fitted divider"></div>
          </table>
        <% end %>
        <div class="ui fitted divider">
          <%= will_paginate @article, renderer: BootstrapPagination::Rails %>
        </div>
      </div>
      <!-- Blog Sidebar Widgets Column -->
      <div class="col-lg-4 col-xs-4">
        <!-- Blog Search Well -->
        <div class="well">
          <h4>Blog Search</h4>
          <div class="input-group">
              <input type="text" class="form-control" name="search" id="search" onchange="HandleIcon()" onpaste="HandleIcon()" onkeyup="HandleIcon()" onkeydown="RedirectToOnClick()" value="<%= @srch%>" placeholder="Search Posts" />
              <span class="input-group-btn">
                              <button class="btn btn-default" type="input" id="commit" name="commit" onclick="RedirectToArticles()">
                                <span id="span_icon" class="<%= if(@srch.nil? || @srch.to_s.empty?)
                                                                 "glyphicon glyphicon-search"
                                                               else "glyphicon glyphicon-remove" end %>"></span>
                              </button>
                          </span>
          </div>
          <!-- /.input-group -->
        </div>
        <!-- Blog Categories Well -->
        <div class="well">
          <h4>Popular Tags</h4>
          <div class="ui horizontal list">
          <% tags =  Tag.order("count DESC").limit(10)%>
          <% if !tags.nil?%>
              <% tags.each do |tag| %>
                  <div class="item">
                    <div class="ui teal tag labels">
                        <% if tag.name == @selected_tag %>
                            <a class="ui label" href="/articles">
                              <%= tag.name %>
                              <i class="delete icon"></i>
                            </a>
                        <%else %>
                            <a class="ui label" href="/articles?popular_tag=[<%= tag.name %>]">
                              <%= tag.name %>
                              <i class="detail"><%= tag.count %></i>
                            </a>
                        <% end %>
                    </div>
                  </div>
              <% end %>
          <% end %>
         </div>
        </div>

        <div class="well">
          <h4>Popular Topics</h4>
          <div class="ui horizontal list">
            <% popularTopics = Article.selectByTopic().order("count DESC").limit(10) %>
            <% if !popularTopics.nil?%>
                <% popularTopics.each do |topic| %>
                    <div class="item">
                      <div class="ui teal tag labels">
                        <% if topic.topic_name == @selected_topic %>
                            <a class="ui label" href="/articles">
                              <%= topic.topic_name %>
                              <i class="delete icon"></i>
                            </a>
                        <%else %>
                            <a class="ui label" href="/articles?popular_topic=<%= topic.topic_name %>">
                              <%= topic.topic_name %>
                              <i class="detail"><%= topic.count %></i>
                            </a>
                        <% end %>
                      </div>
                    </div>
                <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

<script type="text/javascript">
  <!--
  function RedirectToArticlesNew() {
    window.location = "<%= new_article_url %>" ;
  }
  function RedirectToArticles() {
    if(document.getElementById('span_icon').className == "glyphicon glyphicon-remove"){
      document.getElementById('search').value = "";
      document.getElementById('span_icon').className = "glyphicon glyphicon-search"
      window.location = "<%= articles_url %>";
    }
    else
      window.location = "<%= articles_url %>?search="+document.getElementById('search').value;
  }
  function RedirectToOnClick() {
    if (event.keyCode == 13)
      window.location = "<%= articles_url %>?search="+document.getElementById('search').value;
  }
  function HandleIcon() {
    if(document.getElementById('search').value.toString().length > 0)
    {
      document.getElementById('span_icon').className = "glyphicon glyphicon-remove";
    }
    else
    {
      document.getElementById('span_icon').className = "glyphicon glyphicon-search"
    }
  }
  //-->
</script>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <!-- Title -->
    <h2 class="page-header"><%= @article.title %></h2>

    <!-- Blog Offer Content Column -->
    <div class="ui buttons">
    <button class="big ui button" onclick="RedirectToArticles()">
    <i class="arrow circle outline left icon"></i>Back</button>
    <% if @article.user == current_user %>
        <div class="or"></div>
        <button class="big ui button" onclick="RedirectToEdit()">
          <i class="edit left icon"></i>Edit</button>
        <div class="or"></div>
        <button class="big ui button" data-toggle="modal" data-target="#myModal" ><i class="remove icon"></i>Delete</button>
    <% end %>
    </div>

    <hr>

    <!-- Date/Time and posted by who-->
    <p><span class="glyphicon glyphicon-time"></span> Posted on <%= @article.created_at.to_datetime.strftime("%b %d, %Y") %> by <a href="<%= profile_path(@article.user_id) %>"><%= @article.user.username %></a></p>
    <hr>

    <% if !@article.topic.nil? %>
      <p><i class="comment outline icon"></i> <%= @article.topic.topic_name %></p>
    <% end %>
    <table>
      <tr>
        <%if !current_user.nil?%>
        <td>
          <div id="main">
            <div id="inline">
              <% if current_user.voted_up_on? @article %>
                  <a id="inline" class="ui big disabled positive icon button"  href="<%= articles_path %>/like/<%= @article.id %>"><i class="thumbs outline up icon"></i></a>
              <% else%>
                  <a id="inline" class="ui big positive icon button"  href="<%= articles_path %>/like/<%= @article.id %>"><i class="thumbs outline up icon"></i></a>
              <%end%>
            </div>
            <br/>
            <div id="inline">
              <a id="inline" class="ui big label"><%=@article.get_upvotes.size - @article.get_downvotes.size %></a>
            </div>
            <br/>
            <div id="inline">
              <% if current_user.voted_down_on? @article %>
                  <a id="inline" class="ui big disabled negative icon button" href="<%= articles_path %>/dislike/<%= @article.id %>"><i class="thumbs outline down icon"></i></a>
              <% else%>
                  <a id="inline" class="ui big negative icon button" href="<%= articles_path %>/dislike/<%= @article.id %>"><i class="thumbs outline down icon"></i></a>
              <%end%>
              </div>
          </div>
        </td>
        <%end%>
        <td>
          <p> <%= @article.text.html_safe %> </p>
        </td>
      </tr>
    </table>
    <% if !@article.article_attachments.first.nil? %>
        <p><i class="attach icon"></i> <a href="../files/<%= @article.article_attachments.first.id.to_s %>/<%=@article.article_attachments.first.attach_file_file_name%>" ><%=@article.article_attachments.first.attach_file_file_name%></a> </p>
    <% end %>

    <% if !@article.accepted_comment_id.nil? %>
        <div class="ui positive icon message">
          <i class="thumbs outline up icon"></i>
          <div class="content">
            <div class="header">
              Best Contribution
              <hr id="mgSmall">
            </div>
            <p>
            <% cmmt = Comment.find(@article.accepted_comment_id) %>
            <div class="media">
              <% if User.find(cmmt.user_id).profile_pic_file_name.nil? %>
                  <a class="pull-left" href="<%= profile_path(cmmt.user_id)%>">
                    <%= image_tag('/Profile_Avatar.png', :id =>"Image_Tag_Thumbnail", :class =>"media-object", :alt => "No Image") %>
                  </a>
              <%else%>
                  <a class="pull-left" href="<%= profile_path(cmmt.user_id)%>">
                    <%= image_tag(User.find(cmmt.user_id).profile_pic,:id =>"Image_Tag_Thumbnail", :alt => "No Image") %>
                  </a>
              <%end%>

              <div class="media-body">
                <h2 class="media-heading"><%= User.find(cmmt.user_id).username  %>
                  <small><%= cmmt.created_at.to_datetime.strftime("%b %d, %Y at %r")  %></small>
                </h2>
                <%= cmmt.comment_body.html_safe  %>
              </div>
            </div>
            </p>
          </div>
        </div>
    <% end %>


    <!-- Comment -->
    <% if @article.count_comments != 0 %>
      <h3 class="page-header">Comments</h3>
      <% @article.comment.each do |comment| %>
            <% if !comment.user_id.nil? %>
                <% if comment.id != @article.accepted_comment_id %>
                    <div class="media">
                    <% if User.find(comment.user_id).profile_pic_file_name.nil? %>
                        <a class="pull-left" href="<%= profile_path(comment.user_id)%>">
                          <%= image_tag('/Profile_Avatar.png', :id =>"Image_Tag_Thumbnail", :class =>"media-object", :alt => "No Image") %>
                        </a>
                    <%else%>
                        <a class="pull-left" href="<%= profile_path(comment.user_id)%>">
                          <%= image_tag(User.find(comment.user_id).profile_pic,:id =>"Image_Tag_Thumbnail", :alt => "No Image") %>
                        </a>
                    <%end%>
                    <div class="media-body">
                      <h2 class="media-heading"><%= User.find(comment.user_id).username  %>
                        <small><%= comment.created_at.to_datetime.strftime("%b %d, %Y at %r")  %></small>
                          <% if !current_user.nil? && current_user.id == @article.user_id && current_user.id == comment.user_id  %>
                            <div class="ui buttons pull-right">
                              <a href="<%= article_path(@article.id) %>/chooseComment/<%=comment.id%> "><button class="big ui positive button"><i class="check circle outline icon"></i>Best Contribution </button></a>
                              <div class="or"></div>
                              <button class="big ui button" data-toggle="modal" data-comment-id="<%= comment.id  %>" data-target="#myCommentDeleteModal" ><i class="remove icon"></i>Delete</button>
                            </div>
                          <% elsif !current_user.nil? && current_user.id == @article.user_id %>
                            <div class="ui buttons pull-right">
                              <a href="<%= article_path(@article.id) %>/chooseComment/<%=comment.id%> "><button class="big ui positive button"><i class="check circle outline icon"></i>Best Contribution </button></a>
                            </div>
                           <% elsif !current_user.nil? && current_user.id == comment.user_id  %>
                            <button class="big ui button pull-right" data-toggle="modal" data-comment-id="<%= comment.id  %>" data-target="#myCommentDeleteModal" ><i class="remove icon"></i>Delete</button>
                          <%end%>
                      </h2>
                      <%= comment.comment_body.html_safe  %>
                    </div>
                  </div>
                  <hr id="mgSmall">
                <%end%>
              <%end%>
          <%end%>
      <%end%>

    <br/>

    <!-- Comments Form -->
    <div class="well">
      <h3>Leave a Comment:</h3>
      <%= form_for([@article, @article.comment.build]) do |f| %>
          <p>
            <%= f.text_area :comment_body, class:'redactor form-control' %>
          </p>
          <p>
            <button type="submit" name="commit"  class="huge ui positive icon button">
              <i class="save icon"></i>Add Comment</button>
          </p>
      <% end %>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Delete Article</h4>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete the article?</p>
          </div>
          <div class="modal-footer">
            <a rel="nofollow" data-method="delete" href="<%= articles_path %>/<%= @article.id %>">
              <button class="big ui button"><i class="checkmark icon" ></i>Yes</button>
            </a>
            <button type="button" class="big ui button" data-dismiss="modal"><i class="remove icon"></i>No</button>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myCommentDeleteModal" role="dialog">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Delete Comment</h4>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete this comment?</p>
          </div>
          <div class="modal-footer">
            <a rel="nofollow" data-method="delete" href="">
              <button class="big ui button"><i class="checkmark icon" ></i>Yes</button>
            </a>
            <button type="button" class="big ui button" data-dismiss="modal"><i class="remove icon"></i>No</button>
          </div>
        </div>
      </div>
    </div>


  </div>


  <script>

    function RedirectToArticles() {
      window.location = "<%= articles_url %>"
    }
    function RedirectToEdit() {
      window.location = "<%= edit_article_url %>"
    }

    $('#myCommentDeleteModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget) // Button that triggered the modal
      var commentId = button.data('comment-id') // Extract info from data-* attributes
      // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
      // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      var modal = $(this)
      modal.find('.modal-footer a').attr("href", "<%=article_comments_path(@article.id)  %>/"+commentId);
    })

  </script>

</div>

