config/routes.rb
Rails.application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  get 'profile/index'
  get 'profile/edit'
  patch 'profile/update'
  put 'profile/update'
  get 'profile/change_password'
  patch 'profile/update_password'
  put 'profile/update_password'

  post 'comments/delete'

  resources :profile

  resources :articles do
    resources :comments
  end

  resources :offers do
    resources :offer_comments
  end

  get 'welcome/index'
  get 'welcome/about_us'
  root 'welcome#index'

  get 'signup' => 'signup#index'
  post 'signup' => 'signup#create'

  get 'articles/new' => 'articles#index'
  post 'articles/new' => 'articles#create'

  get 'articles/:id/chooseComment/:commentId' => 'articles#AddBestComment'

  get 'login' => 'sessions#index'
  post 'login' => 'sessions#login'
  delete 'logout' => 'sessions#logout'

  get ':controller(/:action)'
  get ':controller(/:action(/:id))(.:format)'

  get 'password_resets/index'
  get 'password_resets/new'
  get 'password_resets/index'
  post 'password_resets/index'
  get 'password_resets/create'
  post 'password_resets/create'
  post 'password_resets/edit'
  get 'password_resets/update'
  post 'password_resets/update'

  get 'account_activations/show'
  post 'account_activations/show'

  resources :account_activations, only: [:index]











end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
  def about_us
    @Names = ["John Jack","Neetha","Sharath","Atezaz","Salman"]
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about_us.html.erb
<div class="container">
	<h1>About us</h1>
	<p>
	This website was  developed by:
	</p>
	<ul>
		<% @Names.each do |name| %>
		<li><%= name %></li>
		<% end %>
	</ul>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <!-- Jumbotron Header -->
  <header class="jumbotron hero-spacer">
    <div class="row">
      <table align="center">
        <tr>
          <td><img align="center" src="/assets/favicon.png" alt="logo"></td>
          <td> <h1 align="center">Corner 4 Students</h1></td>
        </tr>
      </table>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <p>Here you can find a community that will help you with your university topics since you will be able to post a question on anything in mind, as well as you can buy, sell offers and exchange books.</p>
        <a class="huge ui teal icon button" href=" <%= articles_url %>">Go to Forum</a></h2>
        <a class="huge ui teal icon button" href="<%= offers_url %>"?From=ads>Go to Ads</a>
      </div>
    </div>
  </header>
  <!-- Add a Grid Example about showing recent articles  -->
  <div id="grid" class="container-fluid bg-grey">
    <div class="row" >
      <div class="col-md-6 col-sm-6 col-xs-12">
        <h2>Recent Articles</h2>
        <% articles = Article.order("created_at DESC").limit(4) %>
        <% if !articles.nil? %>
            <table width="100%">
              <% articles.each do |article| %>
                <tr>
                    <td>
                      <a href="<%= article_path(article.id)%>"><%= article.title %>  </a>
                    </td>
                    <td>
                      <h6 class="pull-right" >Posted <%= time_ago_in_words(article.created_at)%> ago</h6>
                    </td>
                </tr>
              <% end%>
            </table>
        <% end%>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <h2>Recent Offers</h2>
        <% offers = Offer.order("created_at DESC").limit(4) %>
        <% if !offers.nil? %>
            <table width="100%">
              <% offers.each do |offer| %>
                  <tr>
                    <td>
                      <a href="<%= offer_path(offer.id) %>"><%= offer.title %>  </a>
                    </td>
                    <td>
                      <h6 class="pull-right" >Posted <%= time_ago_in_words(offer.created_at)%> ago</h6>
                    </td>
                  </tr>
              <% end%>
            </table>
        <% end%>
      </div>
    </div>
  </div>



  <div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
    <div class="container">
      <div class="navbar-text pull-left">
        <p>© 2015 Repunit Prime</p>
      </div>
      <div class="navbar-text pull-right">
        <p>Find out more <%= link_to "About us", welcome_about_us_path %></p>
      </div>
    <!--<div class="navbar-text pull-right">-->
        <!--<a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>-->
        <!--<a href="#"><i class="fa fa-twitter fa-2x"></i></a>-->
        <!--<a href="#"><i class="fa fa-google-plus fa-2x"></i></a>-->
      <!--</div>-->
    </div>
  </div>

</div>