config/routes.rb
Rails.application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  get 'profile/index'
  get 'profile/edit'
  patch 'profile/update'
  put 'profile/update'
  get 'profile/change_password'
  patch 'profile/update_password'
  put 'profile/update_password'

  post 'comments/delete'

  resources :profile

  resources :articles do
    resources :comments
  end

  resources :offers do
    resources :offer_comments
  end

  get 'welcome/index'
  get 'welcome/about_us'
  root 'welcome#index'

  get 'signup' => 'signup#index'
  post 'signup' => 'signup#create'

  get 'articles/new' => 'articles#index'
  post 'articles/new' => 'articles#create'

  get 'articles/:id/chooseComment/:commentId' => 'articles#AddBestComment'

  get 'login' => 'sessions#index'
  post 'login' => 'sessions#login'
  delete 'logout' => 'sessions#logout'

  get ':controller(/:action)'
  get ':controller(/:action(/:id))(.:format)'

  get 'password_resets/index'
  get 'password_resets/new'
  get 'password_resets/index'
  post 'password_resets/index'
  get 'password_resets/create'
  post 'password_resets/create'
  post 'password_resets/edit'
  get 'password_resets/update'
  post 'password_resets/update'

  get 'account_activations/show'
  post 'account_activations/show'

  resources :account_activations, only: [:index]











end

app/models/offer.rb
class Offer < ActiveRecord::Base

  belongs_to :user
  has_many :offer_comments

  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :image,
            attachment_size: { less_than: 5.megabytes }

  # Method used to Search for offers
  def self.searchOffersForSale(search)
    where("(title LIKE ? OR detail LIKE ? OR tags LIKE ?) AND forSale = 'sale'", "%#{search}%","%#{search}%","%#{search}%")
  end

  # Method used to Search for offers
  def self.searchOffersForExchange(search)
    where("(title LIKE ? OR detail LIKE ? OR tags LIKE ? OR bookexpected LIKE ? ) AND forSale = 'exchange'", "%#{search}%","%#{search}%","%#{search}%","%#{search}%")
  end

  def self.searchByTagForSale(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("tags_search LIKE ? AND forSale = 'sale'","%#{search}%")
  end

  def self.searchByTagForExchange(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("tags_search LIKE ? AND forSale = 'exchange'","%#{search}%")
  end
  
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  # add authentication for all actions
  before_filter :validate_if_user_logged_in, only: [:new ,:create ,:edit, :update, :destroy]

  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index

    if params[:search]
      if params[:ComingFrom] == 'Exchange'
        @Offers = Offer.where("forSale = 'sale' ").order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
        @OfferExchanges = Offer.searchOffersForExchange(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
        @srch1 = params[:search]
      else
        @Offers = Offer.searchOffersForSale(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
        @OfferExchanges = Offer.where("forSale = 'exchange' ").order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
        @srch = params[:search]
      end
    elsif !params[:popular_tag].nil?
      if params[:ComingFrom].nil?
        redirect_to offers_path
      else
        if params[:ComingFrom] == 'Sale'
          @Offers = Offer.searchByTagForSale(params[:popular_tag]).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
          @OfferExchanges = Offer.where("forSale = 'exchange' ").order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
          @selected_tag = params[:popular_tag].to_s.remove('[',']')
        else
          @Offers = Offer.where("forSale = 'sale' ").order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
          @OfferExchanges = Offer.searchByTagForExchange(params[:popular_tag]).order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
          @selected_tag1 = params[:popular_tag].to_s.remove('[',']')
        end
      end
    else
      @Offers = Offer.where("forSale = 'sale' ").order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
      @OfferExchanges = Offer.where("forSale = 'exchange' ").order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    end

    if params[:ComingFrom] == 'Exchange'
      @ComingFromExchange = true
    end

  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    if params[:Contact_comment] && current_user
      offer = Offer.find(params[:id])
      UserMailer.contact_seller(offer.user,params[:Contact_name],params[:Contact_Email],params[:Contact_comment],offer.id.to_s).deliver_now
      redirect_to offer_path(offer)
    end
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user

    respond_to do |format|
      if @offer.save
        addTagsAndhandleTagCount(@offer)
        format.html { redirect_to @offer }
        if current_user.getEmailNotified
          UserMailer.user_notify_Posted(current_user, @offer.id.to_s).deliver
        end
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update

    prevTags = @offer.tags

    respond_to do |format|
      if @offer.update(offer_params)

        if prevTags != offer_params[:tags]
          handleTagUpdates(prevTags, @offer.forSale)
          addTagsAndhandleTagCount(@offer)
        end

        format.html { redirect_to @offer }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy

    if @offer.tags_search
      split_tags = @offer.tags_search.to_s.remove('[').to_s.split(']');
      split_tags.each do |tag|
        if @offer.forSale == 'sale'
          tempTag = OfferTagForSale.find_by_name(tag)
        else
          tempTag = OfferTagForExchange.find_by_name(tag)
        end
        if(!tempTag.nil?)
          tempTag.count -= 1;
          if(tempTag.count == 0)
            tempTag.destroy
          else
            tempTag.save
          end
        end
      end
    end

    forSale = @offer.forSale

    @offer.destroy
    if forSale =='sale'
      respond_to do |format|
        format.html { redirect_to offers_url}
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to offers_url+'?ComingFrom=Exchange'}
        format.json { head :no_content }
      end
    end

  end

  private

  # Handle Tags
  def addTagsAndhandleTagCount(offer)

    tagsSearch = '';
    #Add count of tags for statistic purposes
    if !offer_params[:tags].nil?
      split_tags = offer_params[:tags].to_s.split(',');
      split_tags.each do |tag|
        if offer.forSale == 'sale'
          tempTag = OfferTagForSale.find_by_name(tag)
        else
          tempTag = OfferTagForExchange.find_by_name(tag)
        end
        tagsSearch += '['+tag+']'

        if(tempTag.nil?)
          if offer.forSale == 'sale'
            tempTag = OfferTagForSale.new()
          else
            tempTag = OfferTagForExchange.new()
          end
          tempTag.name = tag;
          tempTag.count = 1;
        else
          tempTag.count += 1;
        end
        tempTag.save
      end
      offer.tags_search= tagsSearch;
      offer.save
    end
  end

  def handleTagUpdates(prevTags, isForSale)

      split_tags = prevTags.to_s.split(',');
      split_tags.each do |tag|
        if isForSale = 'sale'
          tempTag = OfferTagForSale.find_by_name(tag)
        else
          tempTag = OfferTagForExchange.find_by_name(tag)
        end

        if(!tempTag.nil?)
          tempTag.count -= 1;
          if(tempTag.count == 0)
            tempTag.destroy
          else
            tempTag.save
          end
        end

      end
  end

  def validate_if_user_logged_in
    if !check_login_state
      redirect_to (login_path + '?From='+ request.fullpath)
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = Offer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def offer_params
    params.require(:offer).permit(:title, :detail, :image, :isDeleted, :forSale, :cost, :bookexpected, :tags)
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/edit.html.erb
<div class="container">
  <h2 class="page-header">Edit Offer</h2>

  <div class="ui buttons">
    <button class="big ui button" onclick="RedirectToOffer()">
      <i class="arrow circle outline left icon"></i>Back</button>
  </div>

    <hr>

  <%= form_for @offer, html: {multipart: true} do |f| %>
      <% if @offer.errors.any? %>
          <div class="alert alert-danger" id="error_explanation">
            <h2><%= pluralize(@offer.errors.count, "error") %> : </h2>

            <ul>
              <% @offer.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>


      <% if @offer.forSale == "sale" %>

          <div class=" form-group">
            <label>Title <label id="lbl_red">*</label></label>
            <%= f.text_field :title, class: 'form-control', required: true %>
          </div>

          <div class="form-group">
            <%= f.label :Description %>
            <br>
            <%= f.text_area :detail, class:'redactor form-control', value: @offer.detail.to_s.html_safe, placeholder: "Enter a description for your offer..." %>
          </div>

          <div class="form-group">
            <%= f.label :Image %>
            <%= f.file_field :image, class:'filestyle form-control',data: {buttonBefore: "true"} %>
          </div>


          <div class=" form-group" id="cost">
            <label>Cost</label>
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">€</span>
              <%= f.text_field :cost, id: 'costfld', class:'form-control', required: 'true', aria: {describedBy: "basic-addon1"}, value: @offer.cost, type: "number", step:"0.01" %>
            </div>
          </div>

          <div class="form-group">
            <label for="input_tags">Tags</label>
            <input type="text" id="input_tags" name="offer[tags]" class="demo-default" value="<%= @offer.tags%>">
          </div>


      <% elsif @offer.forSale == "exchange" %>

          <div class=" form-group">
            <label>Title <label id="lbl_red">*</label></label>
            <%= f.text_field :title, class: 'form-control', required: true %>
          </div>

          <div class="form-group">
            <%= f.label :Description %>
            <br>
            <%= f.text_area :detail, class:'redactor form-control', value: @offer.detail.to_s.html_safe, placeholder: "Enter a description for your offer..." %>
          </div>

          <div class="form-group">
            <%= f.label :Image %>
            <%= f.file_field :image, class:'filestyle form-control',data: {buttonBefore: "true"} %>
          </div>

          <div class=" form-group">
            <label>Which book would you like in return? </label>
            <%= f.text_field :bookexpected, class: 'form-control', value: @offer.bookexpected %>
          </div>

          <div class="form-group">
            <label for="input_tags">Tags</label>
            <input type="text" id="input_tags" name="offer[tags]" class="demo-default" value="<%= @offer.tags%>">
          </div>

      <% end %>

      <div class="actions">
        <button type="submit" name="commit"  class="big ui teal labeled icon button">
          <i class="save icon"></i>Save</button>
      </div>

  <% end %>

  <script>

    function RedirectToOffer() {
      window.location = "<%= offers_path %>/<%= @offer.id %>"
    }

    $('#input_tags').selectize({
      delimiter: ',',
      persist: false,
      create: function(input) {
        return {
          value: input,
          text: input
        }
      }
    });

  </script>

</div>

app/views/offers/new.html.erb
<div class="container">
  <h2 class="page-header">New Offer</h2>
  <button id="mrg_btm" class="ui big labeled icon button" onclick="RedirectToOffers()">
    <i class="arrow circle outline left icon"></i>Back</button>

  <%= form_for @offer , html: {multipart: true } do |f|%>
      <% if @offer.errors.any? %>
          <div class="alert alert-danger" id="error_explanation">
            <h2><%= pluralize(@offer.errors.count, "error") %> : </h2>

            <ul>
              <% @offer.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <label>Title <label id="lbl_red">*</label></label>
        <%= f.text_field :title, class:'form-control', required: true %>
      </div>
      <div class="form-group">
        <%= f.label :Description %><br/>
        <textarea id="desc" name="offer[detail]" class='redactor form-control' rows="10" placeholder="Enter a description for your offer..."></textarea>
      </div>
      <div class="form-group">
        <%= f.label :Image %>
        <%= f.file_field :image, class:'filestyle form-control',data: {buttonBefore: "true"} %>
      </div>
      <br/>
      <div class="form-group">
        <label>Is the offer for Sale or Exchange?</label><br/>
        <%= f.radio_button :forSale, "sale" , :checked => true %>
        <%= f.label :Sale, id: 'normalTxt' %><br/>
        <%= f.radio_button :forSale, "exchange" %>
        <%= f.label :Exchange, id: 'normalTxt' %>
      </div>
      <div class=" form-group" id="cost">
        <label>Cost</label>
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon1">€</span>
          <%= f.text_field :cost,id: 'costfld', class:'form-control',required: 'true', aria: {describedBy: "basic-addon1"},value:"0",type: "number",step:"0.01" %>
        </div>
      </div>
      <div class=" form-group" id="exch">
        <label>Which book would you like in return?</label>
        <%= f.text_field :bookexpected, class:'form-control' %>
      </div>
      <div class="form-group">
        <label for="input_tags">Tags</label>
        <input type="text" id="input_tags" name="offer[tags]" class="demo-default">
      </div>

      <div class="actions">
        <button type="submit" name="commit"  class="big ui positive labeled icon button">
          <i class="save icon"></i>Create Offer</button>
      </div>

  <% end %>

</div>




<script type="text/javascript">

  function RedirectToOffers() {
    window.location = "<%= offers_path %>"
  }


  $('#input_tags').selectize({
    delimiter: ',',
    persist: false,
    create: function(input) {
      return {
        value: input,
        text: input
      }
    }
  });


  $(document).ready(function(){

    $("#exch").hide();

    $("input:radio[name='offer[forSale]']").change(function(){

      if(this.value == 'exchange' && this.checked){
        $("#cost").hide();
        $("#costfld").prop("required", false);
        $("#exch").show();
      }else{
        $("#cost").show();
        $("#costfld").prop("required", true);
        $("#exch").hide();
      }

    });
  });

</script>

app/views/offers/show.html.erb
<div class="container">
  <p class="row">
    <!-- Title -->
    <h2 class="page-header"><%= @offer.title %></h2>
    <!-- Blog Offer Content Column -->
    <div class="ui buttons">
      <button class="big ui button" onclick="RedirectToOffers()">
        <i class="arrow circle outline left icon"></i>Back</button>
      <% if @offer.user == current_user %>
          <div class="or"></div>
          <button class="big ui button" onclick="RedirectToEdit()">
            <i class="edit left icon"></i>Edit</button>
          <div class="or"></div>
          <button class="big ui button" data-toggle="modal" data-target="#myModal" ><i class="remove icon"></i>Delete</button>
      <% end %>
    </div>

    <hr>

    <!-- Date/Time and posted by who-->
    <p><span class="glyphicon glyphicon-time"></span> Posted on <%= @offer.created_at.to_datetime.strftime("%b %d, %Y") %> by <a href="<%= profile_path(@offer.user_id) %>"><%= @offer.user.username %></a></p>
    <hr>

  <table style="width:100%; height: 100%">
    <tr>
      <% if @offer.forSale == "sale" %>
          <!--along with td image is also responsive now-->
          <td style="width: 250px">
            <% if @offer.image_file_name.nil? %>
                <span style="margin-right: 20px">  <%= image_tag('/No_Image.png', width: '92%', class: "img-rounded") %> </span>
            <% else %>
                <span style="margin-right: 20px"><%= image_tag(@offer.image, :alt => "No Image", width: '92%', class: "img-rounded") %></span>
            <% end %>
          </td>
          <td style="vertical-align: text-top;">
            <p>
              <strong>Description:</strong>
              <%= @offer.detail.html_safe %>
            </p>
          </td>
    </tr>
    <tr>
      <td class="text-center" style="padding-top: 10px" >
        <% if !current_user.nil? && current_user.id != @offer.user_id  %>
            <div style="margin-top:30px; text-align: center;">
              <button class="big ui blue button" data-toggle="modal" data-target="#Contact"><i class="help circle icon"></i>Contact Seller</button>
            </div>
        <% end %>
      </td>
      <td>
        <strong>Cost:
          <label id="p_Modified_Teal"> <spanp>&#8364;  </spanp>
            <% if @offer.cost.nil? %>
                0
            <% else %>
                <%= @offer.cost %>
            <% end %>
          </label>
        </strong>
      </td>
    </tr>
    <% elsif @offer.forSale == "exchange" %>
          <td style="width: 250px">
            <% if @offer.image_file_name.nil? %>
                <span style="margin-right: 20px">  <%= image_tag('/No_Image.png', width: '92%', class: "img-rounded") %> </span>
            <% else %>
                <span style="margin-right: 20px"><%= image_tag(@offer.image, :alt => "No Image", width: '92%', class: "img-rounded") %></span>
            <% end %>
          </td>
          <td style="vertical-align: text-top;">
            <p>
              <strong>Description:</strong>
              <%= @offer.detail.html_safe %>
            </p>
          </td>
          </tr>
          <tr>
            <td>
              <% if !current_user.nil? && current_user.id != @offer.user_id  %>
                <div style="margin-top:30px; text-align: center">
                  <button class="big ui blue button" data-toggle="modal" data-target="#Contact"><i class="help circle icon"></i>Contact Seller</button>
                </div>
              <% end%>
            </td>
            <td>
              <p>
                <% if @offer.bookexpected.empty?%>
                    Preferable book for exchange: <label id="p_Modified_Grey">&#45;&#45;&#45;&#45;</label>
                <% else %>
                    Preferable book for exchange: <label id="p_Modified_TealExch"><%= @offer.bookexpected %></label>
                <% end %>
              </p>
            </td>
          </tr>

      <% end %>
  </table>

  <hr>
  <!--Add a Comment -->
  <div class="well">
    <h3>Leave a Comment:</h3>
    <%= form_for([@offer, @offer.offer_comments.build]) do |f| %>
        <p>
          <%= f.text_area :comment_body, class: 'form-control' %>
        </p>
        <p>
          <button type="submit" name="commit" class="huge ui positive icon button">
            <i class="save icon"></i>Add Comment
          </button>
        </p>
    <% end %>
  </div>

  <!-- Comment -->
  <% if @offer.offer_comments.count != 0 %>
      <h3 class="page-header">Comments</h3>
      <% @offer.offer_comments.each do |comment| %>
          <% if !comment.user_id.nil? %>
              <div class="media">
                <% if User.find(comment.user_id).profile_pic_file_name.nil? %>
                    <a class="pull-left" href="#">
                      <%= image_tag('/Profile_Avatar.png', :id => "Image_Tag_Thumbnail", :class => "media-object", :alt => "No Image") %>
                    </a>
                <% else %>
                    <a class="pull-left" href="#">
                      <%= image_tag(User.find(comment.user_id).profile_pic, :id => "Image_Tag_Thumbnail", :alt => "No Image") %>
                    </a>
                <% end %>
                <div class="media-body">
                  <h2 class="media-heading"><%= User.find(comment.user_id).username %>
                    <small><%= comment.created_at.to_datetime.strftime("%b %d, %Y at %r") %></small>
                    <% if !current_user.nil? && current_user.id == comment.user_id %>
                        <button class="big ui button pull-right" id="test" data-toggle="modal" data-comment-id="<%= comment.id %>" data-target="#myCommentDeleteModal">
                          <i class="remove icon"></i>Delete
                        </button>
                    <% end %>
                  </h2>
                  <%= comment.comment_body %>
                </div>
              </div>
          <% end %>
      <% end %>
  <% end %>



  <!-- Modal for requesting product -->

  <div class="modal fade" id="Contact" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div id="form-main">
          <div id="form-div">
            <form class="form" id="form1">
              <h1 style="color:white;"> Contact Seller </h1>
              <hr>

              <p class="name">
                <input name="Contact_name"  id="Contact_name" type="text" value="<%= if current_user
                                                                                       current_user.name end %>" class="feedback-input" placeholder="Your Name" />
              </p>

              <p class="email">
                <input name="Contact_Email" id="Contact_Email"  type="text"  value="<%= if current_user
                                                                                          current_user.email end %>" class="feedback-input" placeholder="Your Email" />
              </p>

              <p class="text">
                <textarea name="Contact_comment" id="Contact_comment" class="feedback-input"  placeholder="If you would like to add some comments.."></textarea>
              </p>


              <div class="submit">
                <input type="submit" value="SEND" id="button-blue"/>
                <div class="ease"></div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Delete Article</h4>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to delete the article?</p>
          </div>
          <div class="modal-footer">
            <a rel="nofollow" data-method="delete" href="<%= offers_path %>/<%= @offer.id %>">
              <button class="big ui button"><i class="checkmark icon" ></i>Yes</button>
            </a>
            <button type="button" class="big ui button" data-dismiss="modal"><i class="remove icon"></i>No</button>
          </div>
        </div>
      </div>
    </div>
  <!-- Modal -->
  <div class="modal fade" id="myCommentDeleteModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Delete Comment</h4>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this comment?</p>
        </div>
        <div class="modal-footer">
          <a rel="nofollow" data-method="delete" href="">
            <button class="big ui button"><i class="checkmark icon"></i>Yes</button>
          </a>
          <button type="button" class="big ui button" data-dismiss="modal"><i class="remove icon"></i>No</button>
        </div>
      </div>
    </div>
  </div>

  <script>

    function RedirectToOffers() {
      window.location = "<%= offers_url %>"
    }
    function RedirectToEdit() {
      window.location = "<%= edit_offer_url %>"
    }

    $('#myCommentDeleteModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget) // Button that triggered the modal
      var commentId = button.data('comment-id') // Extract info from data-* attributes
      // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
      // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      var modal = $(this)
      modal.find('.modal-footer a').attr("href", "<%=offer_offer_comments_path(@offer.id)  %>/" + commentId);
    })

  </script>

  </div>
</div>