config/routes.rb
Rails.application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'
  get 'profile/index'
  get 'profile/edit'
  patch 'profile/update'
  put 'profile/update'
  get 'profile/change_password'
  patch 'profile/update_password'
  put 'profile/update_password'

  post 'comments/delete'

  resources :profile

  resources :articles do
    resources :comments
  end

  resources :offers do
    resources :offer_comments
  end

  get 'welcome/index'
  get 'welcome/about_us'
  root 'welcome#index'

  get 'signup' => 'signup#index'
  post 'signup' => 'signup#create'

  get 'articles/new' => 'articles#index'
  post 'articles/new' => 'articles#create'

  get 'articles/:id/chooseComment/:commentId' => 'articles#AddBestComment'

  get 'login' => 'sessions#index'
  post 'login' => 'sessions#login'
  delete 'logout' => 'sessions#logout'

  get ':controller(/:action)'
  get ':controller(/:action(/:id))(.:format)'

  get 'password_resets/index'
  get 'password_resets/new'
  get 'password_resets/index'
  post 'password_resets/index'
  get 'password_resets/create'
  post 'password_resets/create'
  post 'password_resets/edit'
  get 'password_resets/update'
  post 'password_resets/update'

  get 'account_activations/show'
  post 'account_activations/show'

  resources :account_activations, only: [:index]











end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
    <link rel="icon" type="image/png" href="/favicon.png">
		<title>c4s</title>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

		<style>
			/* to limit text to one line in table cells */
			.table {
				table-layout:fixed;
			}
			.oneliner {
				overflow:hidden;
				white-space:nowrap;
				text-overflow:ellipsis;
			}
		</style>
	</head>
	<body>

		<nav class="navbar navbar-inverse navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" data-toggle="collapse" data-target="#navMenu" class="collapsed navbar-toggle">
						<span class="sr-only">Toggle Navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="navMenu">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home", root_url %></li>
            <li><%= link_to "Forum", articles_url %></li>
            <li><%= link_to "Offers", offers_url %></li>
          </ul>
					<ul class="nav navbar-nav navbar-right">
						<% if logged_in %>
						<li class="dropdown">
							<a href="#" data-toggle="dropdown" role="button" class="dropdown-toggle"><%= current_user.username %> <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li>
                  <%= link_to "My Profile", profile_index_path %>
								</li>
								<li>
									<%= link_to "Sign Out", logout_path, method: "delete" %>
								</li>
							</ul>
						</li>
						<% else %>
						<% if login_path && !logged_in %>
						<li>
							<%= link_to "Sign In", login_path %>
						</li>
						<% end %>
						<li>
							<%= link_to "Sign Up", signup_path %>
						</li>
						<% end %>

					</ul>
				</div>
			</div>
		</nav>

		<%= yield %>

		<!-- JS -->
		<!-- <script>
		$('.dropdown-toggle').dropdown();
		</script> -->

	</body>
</html>